#!/bin/bash
scope=@covalent
tag=latest

[[ $1 = 'next' ]] && tag=next || tag=latest

#login into private registry
npm login --scope=$scope

npm publish ${package} --access=public --tag=$tag

#logout when finished
npm logout
echo "Published successfully [scope: $scope]. Use 'npm install [package-name]' in the project you want to use it."
